### ISSUE TITLE
Can't really add line numbers because of how empty lines are treated.

### ISSUE THREAD

**Issue by benlesh** [shikijs/twoslash#65]
I can _almost_ add line numbers like this:

```css
pre.shiki {
  counter-reset: lineNumber;
}

pre.shiki div.line::before {
  user-select: none;
  border-right: 1px solid #404040;
  color: #858585;
  content: counter(lineNumber);
  counter-increment: lineNumber;
  display: inline-block;
  font-variant-numeric: tabular-nums;
  margin-right: 1.2em;
  padding-right: 1.2em;
  text-align: right;
  width: 2.4em;
}
```

The result is SO CLOSE:

![image](https://user-images.githubusercontent.com/1540597/124820888-a9cc5980-df33-11eb-949f-333e91f4583f.png)

However... when I do that it doesn't work properly with empty lines, because this seems to leverage `\n` inside of the `<code>` element, instead of adding something like `<div class="line">&nbsp;</div>` or the like. (NOTE: The reason I suggest the `&nbsp;` here, is because if the div is simply empty, then user's can't really select and copy and paste the newline, TMK.)
